name: flowblu-odoo-test-stack

services:
  # UID/GID = 999(node)
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: flowblu-odoo:17
    networks:
      - flowblu-cloud-prod-net-docker
    ports:
      - "8069:8069"
    volumes:
      - ${PROD_ODOO_CONFIG_FILE_PATH}:/configs/odoo.conf:ro
      - ${HOME}/.docker_volume/prod/odoo/data:/var/lib/odoo
      - ${HOME}/.docker_volume/prod/odoo/extra-addons:/mnt/extra-addons:ro
    # Create the database if not created
    command: ["-i base"]

networks:
  flowblu-cloud-prod-net-docker:
    external: true
